"""
Allow running the module with python -m ap_master_calibration

Generated By: Claude Code (Claude Sonnet 4.5)
"""

import sys

from .calibrate_masters import main

if __name__ == "__main__":
    sys.exit(main())
